# Generated by Django 2.1 on 2018-11-02 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('contactID', models.AutoField(primary_key=True, serialize=False)),
                ('contactName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Defects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partDesc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PartsOrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceType', models.CharField(default='Normal', max_length=255)),
                ('contactID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles_app.Contacts')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMakes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makeDescription', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelDescription', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('serialNumber', models.AutoField(primary_key=True, serialize=False)),
                ('makeCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles_app.VehicleMakes')),
                ('modelCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles_app.VehicleModels')),
            ],
        ),
        migrations.AddField(
            model_name='servicebookings',
            name='serialNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles_app.Vehicles'),
        ),
        migrations.AddField(
            model_name='partsorderlist',
            name='bookingID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles_app.ServiceBookings'),
        ),
        migrations.AddField(
            model_name='partsorderlist',
            name='partID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles_app.Parts'),
        ),
        migrations.AddField(
            model_name='defects',
            name='serialNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles_app.Vehicles'),
        ),
    ]
